project_id = "ywcgburxzwukjtqxuhyr"

[functions.whatsapp-cloud-webhook]
verify_jwt = false

[functions.expirar-giftbacks]
verify_jwt = false

[functions.processar-comunicacoes-giftback]
verify_jwt = false

[functions.enviar-teste-comunicacao-giftback]
verify_jwt = true
